spring.application.name=reservation

spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always

logging.level.org.springframework.security=TRACE

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000